# Generated by Django 4.2.17 on 2024-12-30 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="band",
            name="biography",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="genre",
            field=models.CharField(
                max_length=5,
                null=True,
                verbose_name=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                    ("E", "Electronic"),
                    ("H", "House"),
                    ("DH", "Deep House"),
                    ("MT", "Minimal Tech"),
                    ("T", "Techno"),
                    ("C", "Classic"),
                    ("PE", "Progressive Electronic"),
                    ("IR", "Indie Rock"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="band",
            name="official_homepage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="year_formed",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2021),
                ],
            ),
        ),
    ]
