# Generated by Django 4.2.17 on 2024-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_alter_band_biography_alter_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                default="R",
                max_length=2,
                verbose_name=[
                    ("R", "Records"),
                    ("C", "Clothing"),
                    ("P", "Posters"),
                    ("M", "Miscellaneous"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                default="HH",
                max_length=2,
                verbose_name=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                    ("E", "Electronic"),
                    ("H", "House"),
                    ("DH", "Deep House"),
                    ("MT", "Minimal Tech"),
                    ("T", "Techno"),
                    ("C", "Classic"),
                    ("PE", "Progressive Electronic"),
                    ("IR", "Indie Rock"),
                ],
            ),
        ),
    ]
