# Generated by Django 4.2.17 on 2024-12-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_description_listing_sold_listing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="band",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.band",
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                    ("E", "Electronic"),
                    ("H", "House"),
                    ("DH", "Deep House"),
                    ("MT", "Minimal Tech"),
                    ("T", "Techno"),
                    ("C", "Classic"),
                    ("PE", "Progressive Electronic"),
                    ("IR", "Indie Rock"),
                ],
                default="HH",
                max_length=2,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("R", "Records"),
                    ("C", "Clothing"),
                    ("P", "Posters"),
                    ("M", "Miscellaneous"),
                ],
                default="R",
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
